version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:42"
    assignees:
      - pfichtner
  - package-ecosystem: maven
    directory: "/examples"
    schedule:
      interval: "daily"
      time: "04:42"
    assignees:
      - pfichtner
  - package-ecosystem: maven
    directory: "/runtime/api"
    schedule:
      interval: "daily"
      time: "04:42"
    assignees:
      - pfichtner
  - package-ecosystem: maven
    directory: "/teavm-backend/llvm"
    schedule:
      interval: "daily"
      time: "04:42"
    assignees:
      - pfichtner
