<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.pfichtner</groupId>
    <artifactId>espressomachine-examples</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.pfichtner</groupId>
                <artifactId>espressomachine-api</artifactId>
                <version>0.1.0-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <sourceDirectory>src</sourceDirectory>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.16.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <modules>
        <module>../runtime/api</module>
        <module>add</module>
        <module>blink</module>
        <module>controlflow</module>
        <module>delay-time</module>
        <module>enum</module>
        <module>memory</module>
        <module>objects</module>
        <module>oop-blink</module>
        <module>serial</module>
        <module>echo</module>
        <module>setup-loop</module>
        <module>analog-read</module>
        <module>analog-blink</module>
        <module>pwm-fade</module>
        <module>random</module>
        <module>java-random</module>
        <module>java-math</module>
        <module>digitalread</module>
        <module>functions</module>
        <module>millis-blink</module>
    </modules>
</project>
